<?php

namespace Repository;

/**
 * DomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomRepository extends \Doctrine\ORM\EntityRepository
{
    public function pobierzWszystko()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('d')
            ->from('Entity\Dom', 'd')
            ->join('d.nieruchomosc', 'n');
            //dd($qb->getQuery()->getSQL());
        return $qb->getQuery()->getResult();
        //dd($qb->getQuery()->getSQL());
    }
}
